language: python
python:
  - "3.7"
dist: xenial
sudo: true
install:
  - pip install -r requirements.txt
script:
  - ./run_tests
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres