#!/usr/bin/env bash

coverage run --branch --source=tiger_leagues -m py.test tests/ --disable-pytest-warnings --showlocals -vvl
coverage html
open htmlcov/index.html

# Other notes

# To run pytest with a specific file..
# pytest -vvl /path/to/test_file.py